require 'muzang-plugins/version'
require 'muzang-plugins/helpers'

require 'muzang-plugins/muzang-eval'
require 'muzang-plugins/muzang-livereload'
require 'muzang-plugins/muzang-meme'
require 'muzang-plugins/muzang-motd'
require 'muzang-plugins/muzang-nerdpursuit'
require 'muzang-plugins/muzang-plusone'
require 'muzang-plugins/muzang-reddit'
require 'muzang-plugins/muzang-rubygems'
require 'muzang-plugins/muzang-soupirc'
